TRUNCATE TABLE public.situation RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.texte RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.localisation RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.etablissement RESTART IDENTITY CASCADE;