name: Publishing

on:
  #  release:
  #    types: [prereleased]
  push:
    branches: [ release ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build
        run: ./gradlew clean build

      - name: Prepare release
        env:
          USERNAME: ${{ github.actor }}
          ACTOR_EMAIL: ${{ secrets.ACTOR_EMAIL }}
          GITHUB_REF: ${{ github.GITHUB_REF }}
        run: |
          git config user.name $USERNAME
          git config user.email $ACTOR_EMAIL

      - name: Release
        run: |
          CURRENT_VERSION=$(./gradlew -q printVersion)
          MAJOR_VERSION=$(echo "$CURRENT_VERSION" | cut -d "." -f1)
          CURRENT_MINOR_VERSION=$(echo "$CURRENT_VERSION" | cut -d "." -f2 | cut -d "-" -f1)
          ./gradlew release \
          -Prelease.useAutomaticVersion=true \
          -Prelease.releaseVersion="$(echo "$CURRENT_VERSION" | cut -d "-" -f1)" \
          -Prelease.newVersion="$MAJOR_VERSION.$((CURRENT_MINOR_VERSION+1))-SNAPSHOT"

      - name: Publish to GitHub Packages
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_URL: ${{ github.repository }}
        run: ./gradlew publish
